### Basic Info Config
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  messages:
    encoding: UTF-8
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qrcode?characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password:

server:
  servlet:
    context-path: /qrcode
  tomcat:
    uri-encoding: UTF-8
  port: 8090

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lushihao.qrcode.entity